In [2]:
import pandas as pd
import numpy as np

In [4]:
# Load datase
df = pd.read_csv('top_1000_wallet_scores.csv')

In [14]:
df.head(1000)

,Unnamed: 0,first_tx_time,last_tx_time,account_age_days,avg_hours_between_txs,std_hours_between_txs,total_transactions,PCA1,PCA2,cluster,credit_score
0,0x29fe7d60ddf151e5b52e5fab4f1325da6b2bd958,-1.115836,-0.520740,1.380475,-0.357458,-0.290853,106.874189,4.683019,2.728527,3,100.00
1,0xaa6e8127831c9de45ae56bb1b0d4d4da6e5665bd,1.006652,1.855969,2.553280,-0.355780,-0.301320,56.805223,4.757346,-0.309733,0,59.08
2,0x00000000001876eb1444c986fd502e618c587430,-1.106095,-0.520802,1.355795,-0.356534,-0.278275,48.875500,2.067907,1.903751,0,51.43
3,0xa2b47e3d5c44877cca798226b7b8118f9bfb7a56,-1.029995,-0.520794,1.164346,-0.356383,-0.274199,40.121672,1.596453,1.675350,0,43.94
4,0xf859a1ad94bcf445a406b892ef0d3082f4174088,1.344375,1.856874,1.706030,-0.354731,-0.310197,28.547573,3.130967,-1.182985,0,34.73
...,...,...,...,...,...,...,...,...,...,...,...
995,0xa4517a2b21f85f6a6a63601cea7fa4e34da92856,0.777264,0.981613,0.734360,-0.157651,-0.167193,0.198356,0.926938,-0.920699,1,10.00
996,0x241e1aac00ef9b5f8f22a9bd63c8e6b05bc709ba,1.109894,1.393740,1.026832,-0.044645,0.078902,0.143415,1.532499,-1.162780,1,10.00
997,0xffc5924dd727e6f081ef16b68403b8b322d870ec,-1.113734,-1.040883,-0.050206,-0.337284,-0.283136,0.784386,-1.077806,1.101032,2,10.00
998,0x58ad03b52aca614be263f34305b4659a66e4725a,1.003954,1.544592,1.706775,0.066114,1.036854,0.161729,2.434955,-0.625632,0,9.99
999,0xe9947f9d6137be1efc8525384c49e964aeb4bcd9,0.698878,1.104129,1.267325,-0.139081,0.767993,0.289923,1.698117,-0.462552,0,9.99